apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pezzo.fullname" . }}-proxy
  labels:
    {{- include "pezzo.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pezzo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: proxy
  template:
    metadata:
      labels:
        {{- include "pezzo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: proxy
    spec:
      containers:
        - name: {{ .Chart.Name }}-proxy
          image: "{{ .Values.image.repository }}/proxy:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- range $key, $value := .Values.pezzo.proxy.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
