apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pezzo.fullname" . }}-prisma-migrate
  labels:
    {{- include "pezzo.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "pezzo.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: prisma-migrate
          image: "{{ .Values.image.repository }}/server:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c", "npx prisma migrate deploy"]
          env:
            {{- range $key, $value := .Values.prismaMigrate.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "pezzo.fullname" . }}-secrets
                  key: supertokens-connection-uri
