apiVersion: v1
kind: Service
metadata:
  name: {{ include "pezzo.fullname" . }}-console
  labels:
    {{- include "pezzo.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pezzo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: console
