# Default values for pezzo
replicaCount: 1

image:
  repository: ghcr.io/pezzolabs/pezzo
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Pezzo specific values
pezzo:
  server:
    env:
      SUPERTOKENS_CONNECTION_URI: "http://{{ .Release.Name }}-supertokens:3567"
      CLICKHOUSE_HOST: "{{ .Release.Name }}-clickhouse"
      REDIS_URL: "redis://{{ .Release.Name }}-redis-stack-server:6379"
      KMS_LOCAL_ENDPOINT: "http://{{ .Release.Name }}-local-kms:9981"

  console:
    env: {}
  proxy:
    env: {}

clickhouseMigrate:
  env:
    CLICKHOUSE_HOST: "{{ .Release.Name }}-clickhouse"
    CLICKHOUSE_PORT: "8123"

prismaMigrate:
  env: {}

postgres:
  enabled: true
  service:
    port: 5432
  persistence:
    enabled: true
    storageClass: ""
    size: 8Gi

redis:
  enabled: true
  service:
    port: 6379
  persistence:
    enabled: true
    storageClass: ""
    size: 2Gi

clickhouse:
  enabled: true
  service:
    ports:
      http: 8123
      native: 9000
      mysql: 9004
  persistence:
    enabled: true
    storageClass: ""
    size: 10Gi

supertokens:
  enabled: true
  postgresql:
    enabled: false
  service:
    port: 3567

localKms:
  enabled: true
  service:
    port: 9981
  env:
    PORT: "9981"
    KMS_REGION: "us-east-1"

# Secrets configuration
secrets:
  postgres:
    user: postgres
    password: changeme
  clickhouse:
    user: default
    password: changeme
  supertokens:
    connectionURI: "postgresql://postgres:changeme@{{ .Release.Name }}-postgresql:5432/supertokens"
  localKms:
    backingKeys:
      - 5cdaead27fe7da2de47945d73cd6d79e36494e73802f3c

# External services configuration
externalServices:
  postgres:
    host: ""
    port: 5432
  redis:
    host: ""
    port: 6379
